server:
  port: 8085
  address: 0.0.0.0

FireflyMall:
  db:
    host: localhost
    port: 3306

alipay:
  # 支付宝网关
  GATEWAY: "https://openapi-sandbox.dl.alipaydev.com/gateway.do"
  # 应用ID
  APPID: "9021000157614438"
  # 应用私钥
  APP_PRIVATE_KEY: "MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCmjJT/H3OzYOCKMjFHtqNZAeH5SbidzpM3osfZ+8yTiux0VY+5GkW/iXn7H+MRoFW99NEyFX+rcwFbLj40d+709w5KXCVEIfbg99vOt8kDYL91tPf/Sr6OX4RFVXAjsj4JyhY0Yh05/JSXPO/Mg92/7PQ/9C4tU1wj20NlB+7S/4AJC37DunQFzOF3Q/XeQtTdhUoS3kIWvsmcerg7ja3pk3pRTMPwXTWvC5NMiEPf6qRn9Z7cmXCzAwYcwMbwPs5qVwcWe7yA3+pDoCNi3shQ+xDWGGanboOFAI1Dr092n98NclP6fLnxhZfvG/Nk8I4CoFzvrCIxkXy161nWi/EJAgMBAAECggEBAI9/40TqQZNVrkIEOyex+o5PK/fRiCsX+Qpfy9hKtxqNAWy+5+Wx+FSuzBYOhGQEhLv1u2Vu1qDPp2R7tIcaqx4P3BU/zbAln4R4qsAy5BRwAKcXdPJW4Vbkf6AJnGR1SDTBFV6vBsWWliS1EVxiZebe8BhGeJ7/Cw2t9ySOsDzFFl8LFiHUO2b0SmsNf0vzp431W9oPzGFu0ezhK4uuD5aBdoYZ+oIjfA65Y4LAVJ94YslUVEzrCvexf6BcfGecVBZbShlh0wBfJiPg8xt74YAZ6FhHN0bB9FgqfowlrQCj1Vq93avoO+j+2bRIbmiZD3fNg6GMIMmD5euvkZibDgECgYEA7tirXHudnidZpIwcwXjVsL8p632GO/8taEOENQ4RfKc1BU4rsdd1wLB0Q8aMqYM7ER6gusfvQPjpGirh4qCr+BsRihSdqNpo7VK5R3iZGDi1EIhvzZhPWb36qCIb8LyWERx0IX04q+djNgP2BUBrl2sjp4QMRssr1aO7xBCMaUECgYEAsoKvlbeWlIsL5+4DpVluOzy929TylifpIs2TiXiU8dzxS+FyVm6ZQp2u0P+ZEnQ86zxHXmtcE8KfUm/grLN0ezwziaKKFKM/8WqbQHytL5ywig1UF9wr/i1TLlUnVnJnPg9MmYxzCZ9vxdRzxh/OjFQtMjCe1eAH8fo4DEy1DckCgYEApEq11O/TA67doqoePZb4ppNYKnw1kZ99hHKsxjHfJXd+qR+UPsiOXvUBhH1W1GNIhgYjWVed43tUHIPSzSjoIcm8ztZPfI6ADn8Qo3D5HggjxDOVdD6IlppviKetwHJ4Z1zDJSYVjWmkfMtMt2AQoh84b0oNh8TJajMuPTeE3gECgYEAk4Fdqa9cZD5JhkqtBJLTfWuBzwc1tVIhWTraMPxMx1a0pOkT28vkJKG7dMPgLtmSBSd4KdM48LMfh7UeyFY5aCOkypRe2RLUoZ5fz3e2e+NUFZ9R3611RMEbPOvsZ4h9O1DVEQR3gnoWmDgnuo1J1bcw6Yo3la9boV4Ltk4kRdECgYAszjG0xtdDPPmW+UaXYWS8YOj9ySJuPwxuoLqzwCVANhNWyh7QZa/QXR3pX8wb/8XfU1kaFdo6kR/AGfDwvyRMUx0sC+0BephO64c4bWcWwmqk+0gnSHbTQ9S76fg7vNhCVrPzjf6ZkWuDUwzPZ+fyIkw4bZrwwHjhQpGzGhwTSA=="
  # 支付宝公钥
  ALIPAY_PUBLIC_KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhlYz5o/XjEYtappBtrtDU8T3SpbFP2JuQS5j6G7MWxJejmBhaU9AotcANnZTCqPW8MMacCV3/Vk9nfIRM4bSNdd7/ZhnlUMYR5MLKXCOT2eqlz65avk2NbZp9WpWf/TZjhfS1cmIvnlLr1p1PAwzI8EuToLUXGgp3AdovqBhO5UMjO+U89liUdlNkXWjdeU+5W8QiG3hsBaFGr0O5W/Nf9Qz1AE7jskW/Pi9cBSIuVPg+6kmYM/jzTtQbbwU+Fezo19ekTSNns7afpDJBzKgqh6225+swUbPIM0gB7+yBFJGmVwH7VL9sWotlHXOiT1nHSwkA8nxf2CVuMIAX8r7VQIDAQAB"
  # 签名类型
  SIGN_TYPE: "RSA2"
  # 字符编码
  CHARSET: "UTF-8"
  # 数据格式
  FORMAT: "json"
  # 同步返回地址
  RETURN_URL: "http://localhost:8080/pay/Alipay/getStatus"
  # 是否为沙箱环境
  SANDBOX: true

