registry {
  # 注册中心类型
  type = "nacos"
  nacos {
    # Nacos 服务器地址
    serverAddr = "server:8848"
    # Nacos 命名空间
    namespace = ""
    # Nacos 分组
    group = "DEFAULT_GROUP"
    # Nacos 应用seata的名称
    application = "seata-server"
    # Nacos 用户名
    username = "nacos"
    # Nacos 密码
    password = "nacos"
    # Nacos 集群
    cluster = "default"
  }
}

config {
  # 配置中心类型
  type = "nacos"
  nacos {
    # Nacos 服务器地址
    serverAddr = "server:8848"
    # Nacos 命名空间
    namespace = ""
    # Nacos 分组
    group = "DEFAULT_GROUP"
    # Nacos 数据ID
    dataId = "seataServer.properties"
    # Nacos 用户名
    username = "nacos"
    # Nacos 密码
    password = "nacos"
  }
}